#my.datasource.url = local.db.com
#my.datasource.username = username
#my.datasource.password = password
#my.datasource.etc.max-connection=1
#my.datasource.etc.timeout = 3500ms
##my.datasource.etc.options = CACHE,ADMIN
my:
  datasource:
    url: local.db.com
    username: local_user
    passoword: local_pw
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL, CACHE